import { useState, useMemo } from 'react';
import {
  Users,
  GraduationCap,
  CheckCircle2,
  AlertTriangle,
  Clock,
  Search,
  ChevronDown,
  ChevronUp,
  X,
  Copy,
  Check,
  FileText,
  TrendingUp,
  Eye,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';

// Import static data generated by sync_pp_evaluations.py
import ppData from '@/data/pp_evaluations.json';

// ============================================================
// Types
// ============================================================

interface DeliverableDef {
  id: string;
  num: number;
  title: string;
  short: string;
  icon: string;
  max_score: number;
}

interface PhaseEntry {
  submitted: boolean;
  status: string;
  comment: string;
  files: { name: string; size: number; mtime: string }[];
  score?: number | null;
  max_score?: number;
  audit_v1?: string;
}

interface DeliverableEntry {
  id: string;
  entrainement: PhaseEntry;
  final: PhaseEntry;
}

interface Synthesis {
  coherence?: string;
  points_forts?: string;
  chantiers?: string;
  message?: string;
}

interface PPLearner {
  id: string;
  num: string;
  nom: string;
  prenom: string;
  full_name: string;
  projet: string;
  category: 'green' | 'yellow' | 'red';
  category_label: string;
  status_priority: string;
  synthesis: Synthesis;
  deliverables: Record<string, DeliverableEntry>;
}

interface PPStats {
  total_learners: number;
  v1_completed: number;
  v1_rate: number;
  v2_submitted: number;
  v2_rate: number;
  categories: { green: number; yellow: number; red: number };
  last_updated: string;
}

// ============================================================
// Helpers
// ============================================================

const deliverablesDef: DeliverableDef[] = ppData.deliverables_def as DeliverableDef[];
const learners: PPLearner[] = ppData.learners as PPLearner[];
const stats: PPStats = ppData.stats as PPStats;

function getStatusBadge(phase: PhaseEntry): { color: string; label: string; icon: React.ReactNode } {
  const s = phase.status || '';
  if (s.includes('Non soumis') || s.includes('🔴')) {
    return { color: 'bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/20', label: 'Non soumis', icon: <AlertTriangle className="w-3 h-3" /> };
  }
  if (s.includes('Excellent') || s.includes('✅')) {
    return { color: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20', label: 'Validé', icon: <CheckCircle2 className="w-3 h-3" /> };
  }
  if (s.includes('🟡') || s.includes('ajust') || s.includes('affiner') || s.includes('structurer') || s.includes('améliorer') || s.includes('granularité')) {
    return { color: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20', label: 'À ajuster', icon: <Clock className="w-3 h-3" /> };
  }
  if (phase.submitted) {
    return { color: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20', label: 'Soumis', icon: <FileText className="w-3 h-3" /> };
  }
  return { color: 'bg-muted text-muted-foreground border-border', label: 'En attente', icon: <Clock className="w-3 h-3" /> };
}

function getCategoryBadge(cat: string) {
  switch (cat) {
    case 'green': return { color: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20', dot: 'bg-emerald-500' };
    case 'yellow': return { color: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20', dot: 'bg-amber-500' };
    case 'red': return { color: 'bg-red-500/10 text-red-600 dark:text-red-400 border-red-500/20', dot: 'bg-red-500' };
    default: return { color: 'bg-muted text-muted-foreground border-border', dot: 'bg-muted-foreground' };
  }
}

// ============================================================
// Component
// ============================================================

export default function DashboardPP() {
  const [searchQuery, setSearchQuery] = useState('');
  const [filterCategory, setFilterCategory] = useState<'all' | 'green' | 'yellow' | 'red'>('all');
  const [expandedLearner, setExpandedLearner] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'entrainement' | 'final'>('entrainement');
  const [copiedMessage, setCopiedMessage] = useState<string | null>(null);

  const filteredLearners = useMemo(() => {
    let result = [...learners];
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      result = result.filter(l =>
        l.full_name.toLowerCase().includes(q) ||
        l.projet.toLowerCase().includes(q) ||
        l.num.includes(q)
      );
    }
    if (filterCategory !== 'all') {
      result = result.filter(l => l.category === filterCategory);
    }
    return result;
  }, [searchQuery, filterCategory]);

  const handleCopyMessage = (msg: string, id: string) => {
    navigator.clipboard.writeText(msg);
    setCopiedMessage(id);
    setTimeout(() => setCopiedMessage(null), 2500);
  };

  const toggleLearner = (id: string) => {
    setExpandedLearner(prev => prev === id ? null : id);
    setActiveTab('entrainement');
  };

  // ============================================================
  // Render
  // ============================================================

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-foreground flex items-center gap-2.5">
            <GraduationCap className="w-7 h-7 text-primary" />
            Projet Professionnel
          </h1>
          <p className="text-xs text-muted-foreground mt-1">
            Monitoring des livrables d'entraînement et de restitution finale · Dernière mise à jour : {new Date(stats.last_updated).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })}
          </p>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
        <Card className="bg-card border-border shadow-xs">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center">
                <Users className="w-4.5 h-4.5 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold text-foreground">{stats.total_learners}</p>
                <p className="text-[11px] text-muted-foreground">Apprenants suivis</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-xs">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-lg bg-emerald-500/10 flex items-center justify-center">
                <CheckCircle2 className="w-4.5 h-4.5 text-emerald-500" />
              </div>
              <div>
                <div className="flex items-baseline gap-1.5">
                  <p className="text-2xl font-bold text-foreground">{stats.categories.green}</p>
                  <span className="text-xs font-semibold text-emerald-600 dark:text-emerald-400">({stats.v1_rate}%)</span>
                </div>
                <p className="text-[11px] text-muted-foreground">Complets V1 (4/4)</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-xs">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-lg bg-amber-500/10 flex items-center justify-center">
                <Clock className="w-4.5 h-4.5 text-amber-500" />
              </div>
              <div>
                <div className="flex items-baseline gap-1.5">
                  <p className="text-2xl font-bold text-foreground">{stats.categories.yellow}</p>
                  <span className="text-xs font-semibold text-amber-600 dark:text-amber-400">({Math.round((stats.categories.yellow / stats.total_learners) * 100)}%)</span>
                </div>
                <p className="text-[11px] text-muted-foreground">Partiels V1 (2-3/4)</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-xs">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-lg bg-red-500/10 flex items-center justify-center">
                <AlertTriangle className="w-4.5 h-4.5 text-red-500" />
              </div>
              <div>
                <div className="flex items-baseline gap-1.5">
                  <p className="text-2xl font-bold text-foreground">{stats.categories.red}</p>
                  <span className="text-xs font-semibold text-red-600 dark:text-red-400">({Math.round((stats.categories.red / stats.total_learners) * 100)}%)</span>
                </div>
                <p className="text-[11px] text-muted-foreground">En retard (1/4)</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border-border shadow-xs col-span-2 sm:col-span-1">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-lg bg-blue-500/10 flex items-center justify-center">
                <TrendingUp className="w-4.5 h-4.5 text-blue-500" />
              </div>
              <div>
                <div className="flex items-baseline gap-1.5">
                  <p className="text-2xl font-bold text-foreground">{stats.v2_submitted}</p>
                  <span className="text-xs font-semibold text-blue-600 dark:text-blue-400">({stats.v2_rate}%)</span>
                </div>
                <p className="text-[11px] text-muted-foreground">Rendus finaux V2</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Search & Filters */}
      <Card className="bg-card border-border shadow-sm">
        <CardContent className="p-4">
          <div className="flex flex-col sm:flex-row gap-3">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Rechercher un apprenant ou un projet..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9 h-9 text-sm bg-background"
              />
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery('')}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground cursor-pointer"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
            <div className="flex gap-1.5">
              {(['all', 'green', 'yellow', 'red'] as const).map(cat => (
                <Button
                  key={cat}
                  variant={filterCategory === cat ? 'default' : 'outline'}
                  size="sm"
                  onClick={() => setFilterCategory(cat)}
                  className={cn(
                    "h-9 text-xs cursor-pointer gap-1.5",
                    filterCategory !== cat && "text-muted-foreground"
                  )}
                >
                  {cat === 'all' && 'Tous'}
                  {cat === 'green' && <><span className="w-2 h-2 rounded-full bg-emerald-500" /> Complets</>}
                  {cat === 'yellow' && <><span className="w-2 h-2 rounded-full bg-amber-500" /> Partiels</>}
                  {cat === 'red' && <><span className="w-2 h-2 rounded-full bg-red-500" /> En retard</>}
                </Button>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Learner Matrix Table */}
      <Card className="bg-card border-border shadow-sm overflow-hidden">
        <CardHeader className="pb-0 px-5 pt-4">
          <CardTitle className="text-sm font-semibold text-foreground flex items-center justify-between">
            <span>Matrice des Livrables ({filteredLearners.length} apprenants)</span>
            <Badge variant="outline" className="text-[10px] font-normal text-muted-foreground border-border">
              Phase actuelle : Entraînement (V1)
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0 mt-3">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow className="border-border hover:bg-transparent">
                  <TableHead className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider w-[40px] pl-5">#</TableHead>
                  <TableHead className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider min-w-[180px]">Apprenant</TableHead>
                  {deliverablesDef.map(d => (
                    <TableHead key={d.id} className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider text-center min-w-[100px]">
                      <div className="flex flex-col items-center gap-0.5">
                        <span>{d.icon}</span>
                        <span className="leading-tight">{d.short}</span>
                      </div>
                    </TableHead>
                  ))}
                  <TableHead className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider text-center w-[90px]">Statut</TableHead>
                  <TableHead className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider text-center w-[50px] pr-5"></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredLearners.map(learner => {
                  const isExpanded = expandedLearner === learner.id;
                  const catBadge = getCategoryBadge(learner.category);
                  return (
                    <>
                      <TableRow
                        key={learner.id}
                        className={cn(
                          "border-border transition-colors cursor-pointer",
                          isExpanded ? "bg-accent/40" : "hover:bg-accent/20"
                        )}
                        onClick={() => toggleLearner(learner.id)}
                      >
                        <TableCell className="text-xs text-muted-foreground font-mono pl-5">{learner.num}</TableCell>
                        <TableCell>
                          <div className="min-w-0">
                            <p className="text-xs font-semibold text-foreground truncate">{learner.full_name}</p>
                            <p className="text-[10px] text-muted-foreground truncate max-w-[240px]">{learner.projet}</p>
                          </div>
                        </TableCell>
                        {deliverablesDef.map(d => {
                          const deliv = learner.deliverables[d.id];
                          if (!deliv) return <TableCell key={d.id} className="text-center"><span className="text-muted-foreground text-[10px]">—</span></TableCell>;
                          const phase = deliv.entrainement;
                          const badge = getStatusBadge(phase);
                          return (
                            <TableCell key={d.id} className="text-center">
                              <Badge variant="outline" className={cn("text-[9px] py-0.5 px-1.5 gap-1 font-normal", badge.color)}>
                                {badge.icon}
                                {badge.label}
                              </Badge>
                            </TableCell>
                          );
                        })}
                        <TableCell className="text-center">
                          <Badge variant="outline" className={cn("text-[9px] py-0.5 px-1.5 gap-1 font-medium", catBadge.color)}>
                            <span className={cn("w-1.5 h-1.5 rounded-full", catBadge.dot)} />
                            {learner.category_label.split('(')[0].trim()}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-center pr-5">
                          <Button variant="ghost" size="sm" className="h-7 w-7 p-0 cursor-pointer text-muted-foreground hover:text-foreground">
                            {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                          </Button>
                        </TableCell>
                      </TableRow>

                      {/* Expanded Detail Panel */}
                      {isExpanded && (
                        <TableRow key={`${learner.id}-detail`} className="bg-accent/20 border-border">
                          <TableCell colSpan={deliverablesDef.length + 4} className="p-0">
                            <div className="px-5 py-4 space-y-4 animate-fade-in">
                              
                              {/* Phase Tabs */}
                              <div className="flex items-center gap-2">
                                <Button
                                  variant={activeTab === 'entrainement' ? 'default' : 'outline'}
                                  size="sm"
                                  onClick={(e) => { e.stopPropagation(); setActiveTab('entrainement'); }}
                                  className="h-8 text-xs cursor-pointer gap-1.5"
                                >
                                  <FileText className="w-3.5 h-3.5" />
                                  Phase 1 — Entraînement (V1)
                                </Button>
                                <Button
                                  variant={activeTab === 'final' ? 'default' : 'outline'}
                                  size="sm"
                                  onClick={(e) => { e.stopPropagation(); setActiveTab('final'); }}
                                  className="h-8 text-xs cursor-pointer gap-1.5"
                                >
                                  <GraduationCap className="w-3.5 h-3.5" />
                                  Phase 2 — Restitution Finale (V2)
                                </Button>
                              </div>

                              {/* Deliverable Cards Grid */}
                              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">
                                {deliverablesDef.map(d => {
                                  const deliv = learner.deliverables[d.id];
                                  if (!deliv) return null;
                                  const phase = activeTab === 'entrainement' ? deliv.entrainement : deliv.final;
                                  const badge = getStatusBadge(phase);
                                  const messageId = `${learner.id}-${d.id}-${activeTab}`;

                                  return (
                                    <Card key={d.id} className="bg-card border-border shadow-xs">
                                      <CardHeader className="pb-2 pt-3 px-3.5">
                                        <div className="flex items-center justify-between">
                                          <div className="flex items-center gap-2">
                                            <span className="text-base">{d.icon}</span>
                                            <CardTitle className="text-xs font-semibold text-foreground">{d.short}</CardTitle>
                                          </div>
                                          <Badge variant="outline" className={cn("text-[9px] py-0.5 px-1.5 gap-1 font-normal", badge.color)}>
                                            {badge.icon}
                                            {badge.label}
                                          </Badge>
                                        </div>
                                      </CardHeader>
                                      <CardContent className="px-3.5 pb-3">
                                        {phase.comment ? (
                                          <div className="space-y-2">
                                            <p className="text-[11px] text-muted-foreground leading-relaxed line-clamp-4 whitespace-pre-line">
                                              {phase.comment}
                                            </p>
                                            <div className="flex items-center gap-1.5">
                                              <Button
                                                variant="ghost"
                                                size="sm"
                                                onClick={(e) => {
                                                  e.stopPropagation();
                                                  handleCopyMessage(phase.comment, messageId);
                                                }}
                                                className="h-6 text-[10px] text-muted-foreground hover:text-foreground cursor-pointer gap-1 px-2"
                                              >
                                                {copiedMessage === messageId ? (
                                                  <><Check className="w-3 h-3 text-emerald-500" /> Copié</>
                                                ) : (
                                                  <><Copy className="w-3 h-3" /> Copier le message</>
                                                )}
                                              </Button>
                                              {phase.files && phase.files.length > 0 && (
                                                <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                                                  <FileText className="w-3 h-3" />
                                                  {phase.files.length} fichier(s)
                                                </span>
                                              )}
                                            </div>
                                          </div>
                                        ) : (
                                          <p className="text-[11px] text-muted-foreground italic">
                                            {activeTab === 'final' ? 'En attente de la restitution finale.' : 'Aucun feedback disponible.'}
                                          </p>
                                        )}
                                        {activeTab === 'final' && phase.score != null && (
                                          <div className="mt-2 flex items-center gap-2 px-2 py-1.5 bg-primary/5 rounded-lg border border-primary/10">
                                            <span className="text-xs font-bold text-primary">{phase.score}/{phase.max_score}</span>
                                            <span className="text-[10px] text-muted-foreground">Note finale</span>
                                          </div>
                                        )}
                                      </CardContent>
                                    </Card>
                                  );
                                })}
                              </div>

                              {/* Synthesis Section */}
                              {learner.synthesis && learner.synthesis.message && (
                                <Card className="bg-primary/5 border-primary/10 shadow-xs">
                                  <CardContent className="p-4">
                                    <div className="flex items-start gap-3">
                                      <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                                        <Eye className="w-4 h-4 text-primary" />
                                      </div>
                                      <div className="space-y-2 min-w-0 flex-1">
                                        <h4 className="text-xs font-semibold text-foreground">Synthèse Globale & Orientation</h4>
                                        {learner.synthesis.coherence && (
                                          <p className="text-[11px] text-muted-foreground leading-relaxed">
                                            <span className="font-semibold text-foreground">Cohérence transversale : </span>
                                            {learner.synthesis.coherence}
                                          </p>
                                        )}
                                        {learner.synthesis.points_forts && (
                                          <p className="text-[11px] text-muted-foreground leading-relaxed">
                                            <span className="font-semibold text-foreground">Points forts : </span>
                                            {learner.synthesis.points_forts}
                                          </p>
                                        )}
                                        {learner.synthesis.chantiers && (
                                          <p className="text-[11px] text-muted-foreground leading-relaxed whitespace-pre-line">
                                            <span className="font-semibold text-foreground">Chantiers prioritaires : </span>
                                            {learner.synthesis.chantiers}
                                          </p>
                                        )}
                                        <div className="flex items-center gap-2 pt-1">
                                          <Button
                                            variant="ghost"
                                            size="sm"
                                            onClick={(e) => {
                                              e.stopPropagation();
                                              handleCopyMessage(learner.synthesis.message || '', `synth-${learner.id}`);
                                            }}
                                            className="h-6 text-[10px] text-muted-foreground hover:text-foreground cursor-pointer gap-1 px-2"
                                          >
                                            {copiedMessage === `synth-${learner.id}` ? (
                                              <><Check className="w-3 h-3 text-emerald-500" /> Copié</>
                                            ) : (
                                              <><Copy className="w-3 h-3" /> Copier le message d'orientation</>
                                            )}
                                          </Button>
                                        </div>
                                      </div>
                                    </div>
                                  </CardContent>
                                </Card>
                              )}

                            </div>
                          </TableCell>
                        </TableRow>
                      )}
                    </>
                  );
                })}
              </TableBody>
            </Table>
          </div>

          {filteredLearners.length === 0 && (
            <div className="py-12 text-center text-muted-foreground">
              <Search className="w-8 h-8 mx-auto mb-3 text-muted-foreground/40" />
              <p className="text-sm font-medium">Aucun apprenant trouvé</p>
              <p className="text-xs mt-1">Essayez de modifier vos critères de recherche ou de filtre.</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
